name: 测试获取密钥
on:
    push:
        branches:
            - main
permissions: read-all
jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - name: 显示secrets密钥
              shell: bash
              env:
                GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY}}
              run: |
                touch ~/.bashrc
                echo export GOOGLE_API_KEY=$GOOGLE_API_KEY >> ~/.bashrc
                cat ~/.bashrc
                source .~/.bashrc
                echo $GOOGLE_API_KEY


