name: 测试获取密钥
env:
    GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY}}
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - name: 显示secrets密钥
              run: |
                echo 'export GOOGLE_API_KEY=$GOOGLE_API_KEY' >> ~/.bashrc
                source .~/.bashrc
                echo $GOOGLE_API_KEY


