name: 测试获取密钥
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - shell: bash
              env:
                GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY}}
              run: |
                export GOOGLE_API_KEY=$GOOGLE_API_KEY
                echo $GOOGLE_API_KEY


